# TensorFlow Core

In [105]:
# connect to the google drive
from google.colab import drive
drive.mount('/content/gdrive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive/


## 0 Preparation

In [106]:
# change the current directory
import os
os.chdir("/content/gdrive/My Drive/TensorFlow_Learning/TensorFlow-Core/01.Intro_to_TensorFlow")
!pwd
!ls

/content/gdrive/My Drive/TensorFlow_Learning/TensorFlow-Core/01.Intro_to_TensorFlow
01.Intro_to_TensorFlow.ipynb


## 1.1 Introduction
TensorFlow GitHub Repository: https://github.com/tensorflow/tensorflow

---

## 1.2 TensorFlow Installation
Please Google it

Update the version of TensorFlow:

`pip install --upgrade tensorflow`

---

## 1.3 Hello World

In [0]:
# import tensorflow
import tensorflow as tf

In [0]:
# tf.constant
message = tf.constant('Hello World!')

In [0]:
# define tf.Session() as sess and run the Session
with tf.Session() as sess:
  print(sess.run(message).decode())
  
# sess.run(message) gets b'Hello World!'

Hello World!


## 1.4 Graphs and Sessions

TensorFlow uses a **dataflow graph** to represent your computation in terms of the dependencies between individual operations. This leads to a low-level programming model in which you first define the dataflow graph, then create a TensorFlow **session** to run parts of the graph across a set of local and remote devices.

**Dataflow** is a common programming model for parallel computing. In a dataflow graph, the nodes represent units of computation(Operation Object), and the edges represent the data consumed or produced by a computation. Each node can have zero or more inputs, but only has one output.

We use the **Session** object to execute the dataflow graph.

In [0]:
# import tensorflow
import tensorflow as tf
# define a dataflow graph of adding two tensors
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
# or v_add = v_1 + v_2

In [2]:
# execute the graph in a session 1
with tf.Session() as sess:
  print(sess.run(v_add))
  
# execute the graph in a session 2
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(v_add))
sess.close()

[3 3 8 7]


We use the `run()` of `tf.Session()` to execute the graph. The resulting value is `fetches`.

```
run(fetches,feed_dict=None,options=None,run_metadata)
```


In [4]:
# getting multiple values
with tf.Session() as sess:
  print(sess.run([v_1,v_2,v_add]))

[array([1, 2, 3, 4], dtype=int32), array([2, 1, 5, 3], dtype=int32), array([3, 3, 8, 7], dtype=int32)]


**Interactive Session** in Jupyter Notebook and Python shell. We could use `eval()` to return the tensor objects directly instead of explicitly returning sessions.

In [5]:
sess = tf.InteractiveSession()

v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = v_1 + v_2

print(v_add.eval())
sess.close()

[3 3 8 7]


## 1.5 Constants, Variables, and Placeholders

*   Constants: immutible tensors.
*   Variables: tensors which need to be updated in a session.
*   Placeholders: used to input values to tensorflow graphs. Can be used with `feed_dict` to input data. Inputting training data.



### 1.5.1 Constants

In [50]:
sess = tf.InteractiveSession()
# scalar constant
t_1 = tf.constant(4)
print(t_1.eval())

4


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [51]:
# vector constant 
t_2 = tf.constant([4,3,2])
print(t_2.eval())

[4 3 2]


In [52]:
# zero/one tensors and data type
zero_t = tf.zeros([2,3],tf.int32)
one_t = tf.ones([2,3],tf.int32)
print(zero_t.eval(),one_t.eval())

[[0 0 0]
 [0 0 0]] [[1 1 1]
 [1 1 1]]


In [53]:
# create matrices of same shape as t_2
a = tf.zeros_like(t_2)
b = tf.ones_like(t_2)
print(a.eval(),b.eval())

[0 0 0] [1 1 1]


In [54]:
# create an arithmetric sequence of numbers
# tf.linspace(start,stop,num)
range_t = tf.linspace(2.5,5.0,5)
print(range_t.eval())

# create a range of numbers
# tf.range(start=0,limit,delta=1)
range_t1 = tf.range(10)
print(range_t1.eval())
range_t2 = tf.range(1,10,3)
print(range_t2.eval())

[2.5   3.125 3.75  4.375 5.   ]
[0 1 2 3 4 5 6 7 8 9]
[1 4 7]


In [69]:
# random normal tensors
t_dist = tf.random_normal([2,3],mean=1.0,stddev=4,seed=12)
print(t_dist.eval())

# truncated normal tensors
t_dist = tf.truncated_normal([1,5],mean=0,stddev=1,seed=12)
print(t_dist.eval())

# random uniform tensors
t_dist = tf.random_uniform([3,2],minval=1,maxval=3,seed=12)
print(t_dist.eval())

[[-0.7465254   4.3799095   0.9527606 ]
 [-2.5376031   0.25889844  1.8478067 ]]
[[-0.43663135  0.84497744 -0.01180986 -0.8844008  -1.938745  ]]
[[2.272305  2.848183 ]
 [2.3525546 2.0042503]
 [2.9222991 2.7713444]]


In [76]:
# random crop on constant tensor
t_con = tf.constant([[1,2,3],[4,5,6]])
t_crop = tf.random_crop(t_con,[1,2],seed=2)
print(t_con.eval())
print(t_crop.eval())

# random crop on constant tensor
t_crop = tf.random_crop(t_dist,[1,2],seed=2)
print(t_dist.eval())
print(t_crop.eval())

[[1 2 3]
 [4 5 6]]
[[5 6]]
[[1.2071614 2.0964448]
 [1.3709106 1.6356249]
 [1.9855075 2.9323611]]
[[2.6849704 1.0731683]]


In [83]:
# random shuffle along the first dimension
t_con = tf.constant([[1,2],[3,4],[5,6]])
t_con = tf.random_shuffle(t_con)
print(t_con.eval())

# set the seed
tf.set_random_seed(54)

[[3 4]
 [5 6]
 [1 2]]


### 1.5.2 Variables
The weights and biases are usually defined as variables.

In [0]:
rand_t = tf.random_uniform([10,10],0,10,seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t)
# print(t_a.eval(),t_b.eval())

In [0]:
# initialize variables with constants
weights = tf.Variable(tf.random_normal([100,100],stddev=2))
bias = tf.Variable(tf.zeros([100]),name='biases')

In [0]:
# initialize variables with other variables
weight2 = tf.Variable(weights.initialized_value(),name='w2')

In [0]:
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init_op)
# Now all variables are initialized.

In [0]:
# use tf.Variable.initializer for initiation
bias = tf.Variable(tf.zeros([100,100]))
with tf.Session() as sess:
  sess.run(bias.initializer)

### 1.5.3 Placeholder
```
tf.placeholder(dtype,shape=None,name=None)
```

In [92]:
x = tf.placeholder("float")
y = 2 * x
data = tf.random_uniform([4,5],10)
with tf.Session() as sess:
  x_data = sess.run(data)
  print(x_data)
  print(sess.run(y,feed_dict = {x:x_data}))

[[1.8789301 8.395227  2.7997818 2.4391274 6.0919366]
 [9.640633  4.8577614 5.630925  3.592085  8.25952  ]
 [7.8826857 9.802353  6.3477306 5.255578  7.604839 ]
 [6.107925  3.4214468 7.8937182 6.7635016 5.0138474]]
[[ 3.7578602 16.790455   5.5995636  4.878255  12.183873 ]
 [19.281265   9.715523  11.26185    7.18417   16.51904  ]
 [15.765371  19.604706  12.695461  10.511156  15.209678 ]
 [12.21585    6.8428936 15.7874365 13.527003  10.027695 ]]


## 1.6 Matrix Operation with TensorFlow

In [107]:
import tensorflow as tf
sess = tf.InteractiveSession()

# Define a 5*5 Identity matrix
I_mat = tf.eye(5)
print(I_mat.eval())

# Define a Variable initialized to a 10*10 identity matrix
X = tf.Variable(tf.eye(10))
X.initializer.run()
print(X.eval())

# Create a random 5*10 matrix
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()

# multiply two matrices
product = tf.matmul(A,X)
print(product.eval())

# create a random matrix of 1s and 0s, size 5*10
b = tf.Variable(tf.random_uniform([5,10],0,2,dtype=tf.int32))
b.initializer.run()
print(b.eval())
b_new = tf.cast(b, dtype=tf.float32)
# cast to float32 data type

# add the two matrices
t_sum = tf.add(product, b_new)
t_sub = product - b_new
print("A*X+b\n",t_sum.eval())
print("A*X-b\n",t_sub.eval())

sess.close()

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[-1.3354905   0.71696675 -0.8435755  -0.8193663   1.1683615  -0.21576583
  -0.8280636  -0.5148073   0.4832368  -0.92351013]
 [-0.7020877  -0.1718816   1.1138556   0.77514285 -0.95567644  0.05196059
  -0.21956676 -0.18843085 -1.7845424   0.45924693]
 [-0.35356784  1.0788745  -1.2692485  -0.12986495  0.773889   -1.6038711
   1.4177587   0.9828396   1.5507712  -1.1320006 ]
 [-0.17343189  0.24132133  0.42067453  1.6038967   0.2965017  -0.12086555
   1.8951447   0.6461727  -0.27532628  0.5131615 ]
 [ 0.18577458 -1.0393796   2.668835   -0.31889123 -1.7778034   0.10490684
  -1.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [108]:
import tensorflow as tf
sess = tf.InteractiveSession()

# Create two random matrices
a = tf.Variable(tf.random_normal([4,5],stddev=2))
b = tf.Variable(tf.random_normal([4,5],stddev=2))

# Elementwise Multiplication
A = a * b

# Multiplication with a scalar 2
B = tf.scalar_mul(2,A)

# Elementwise division
C = tf.div(a,b)
# returned tensor has the same dtype of a

# Elementwise remainder of division
D = tf.mod(a,b)

init_op = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init_op)
  writer = tf.summary.FileWriter('graphs',sess.graph)
  a, b, A_R, B_R, C_R, D_R = sess.run([a,b,A,B,C,D])
  print("a\n",a,"\n b\n",b,"\n a*b\n",A_R,"\n 2*a*b\n",B_R, "\n a/b\n",C_R, "\n a%b\n", D_R)
  writer.close()

sess.close()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


a
 [[ 2.1554463   1.2255551   0.85971034  1.2877957  -1.161726  ]
 [ 1.5740978   1.8133887  -2.1817589  -1.5003074   1.4635514 ]
 [-0.932316   -0.5693516  -2.3576887   1.6802608  -1.9533801 ]
 [ 1.5863876   0.84164685 -2.3700273  -2.693073    0.5888301 ]] 
 b
 [[-3.3409584  -1.7090582  -2.2866967   0.05913589  4.0227184 ]
 [ 1.4007288  -0.21789645 -1.1196263  -1.6768351   0.334733  ]
 [-0.37507787  0.49227813  1.3025357  -2.0285444  -2.4514701 ]
 [-2.7654326   1.0614501   2.7763574  -2.6809614   0.7925444 ]] 
 a*b
 [[-7.2012563  -2.094545   -1.9658967   0.07615495 -4.6732965 ]
 [ 2.204884   -0.39513096  2.4427545   2.515768    0.48989898]
 [ 0.3496911  -0.28027934 -3.0709736  -3.4084837   4.788653  ]
 [-4.3870482   0.89336616 -6.580043    7.2200246   0.46667403]] 
 2*a*b
 [[-14.402513    -4.18909     -3.9317935    0.1523099   -9.346593  ]
 [  4.409768    -0.7902619    4.885509     5.031536     0.97979796]
 [  0.6993822   -0.5605587   -6.1419473   -6.8169675    9.577306  ]
 [ -8.7740965

## 1.7 Using TensorBoard

TensorBoard 1.13.1 at http://1d5352e7b98a:6006 (Press CTRL+C to quit)
